In [20]:
import pandas as pd
import torch
import torch.nn as nn


In [22]:
data = pd.read_csv('./data/jak3_descriptors.csv')
data

Molecule ChEMBL ID                                             Smiles  \
0          CHEMBL385937  Cc1ccc(C(=O)Nc2cccc(C(F)(F)F)c2)cc1-c1ccc2nc(N...   
1         CHEMBL1080111  O=c1[nH]c2cnc(-n3cnc4ccccc43)nc2n1C1CCOc2c(F)c...   
2         CHEMBL1081376  O=c1[nH]c2cnc(-n3cnc4ccccc43)nc2n1C1CCOc2c(Cl)...   
3         CHEMBL3642278            COc1ccc(Nc2nc3c(-c4cn[nH]c4)cccn3n2)cc1   
4         CHEMBL3642348  CN1CCC(c2ccc(Nc3nc4c(Nc5ccccc5S(C)(=O)=O)cccn4...   
...                 ...                                                ...   
3266      CHEMBL5201705  C=CC(=O)Nc1cc(Nc2ncc(Cl)c(O[C@@H]3CO[C@H]4[C@@...   
3267      CHEMBL5192736  C=CC(=O)Nc1cc(Nc2ncc(Cl)c(O[C@@H]3CO[C@H]4[C@@...   
3268      CHEMBL5194482  C=CC(=O)Nc1cccc(Cn2c(=O)ccc3cnc(Nc4ccc(N5CCN(C...   
3269      CHEMBL5088804                  COc1cc(-c2ccc(O)cc2)cc2cnc(N)nc12   
3270      CHEMBL5186701  C=CC(=O)Nc1cccc(Cn2c(=O)ccc3cnc(Nc4ccc(N(C)CCN...   

      pChEMBL Value                                       Molecule  \
0              7.70  <rdkit.Chem.rdchem.Mol object at 0x14ed56730>   
1              7.52  <rdkit.Chem.rdchem.Mol object at 0x16667af80>   
2              6.77  <rdkit.Chem.rdchem.Mol object at 0x16667b220>   
3              6.29  <rdkit.Chem.rdchem.Mol object at 0x16667b290>   
4              6.85  <rdkit.Chem.rdchem.Mol object at 0x16667b300>   
...             ...                                            ...   
3266           8.89  <rdkit.Chem.rdchem.Mol object at 0x1666d9460>   
3267           8.92  <rdkit.Chem.rdchem.Mol object at 0x1666d94d0>   
3268           8.70  <rdkit.Chem.rdchem.Mol object at 0x1666d9540>   
3269           7.40  <rdkit.Chem.rdchem.Mol object at 0x1666d95b0>   
3270           8.51  <rdkit.Chem.rdchem.Mol object at 0x1666d9620>   

      MaxEStateIndex  MinEStateIndex  MaxAbsEStateIndex  MinAbsEStateIndex  \
0          12.917910       -4.483900          12.917910           0.071660   
1          14.243005       -0.439546          14.243005           0.185077   
2          12.889483       -0.245588          12.889483           0.239832   
3           5.152457        0.533437           5.152457           0.533437   
4          12.168844       -3.377002          12.168844           0.235711   
...              ...             ...                ...                ...   
3266       13.863638       -1.178358          13.863638           0.023255   
3267       13.884472       -3.073039          13.884472           0.006903   
3268       12.815756       -0.292129          12.815756           0.172028   
3269        9.348054        0.215911           9.348054           0.215911   
3270       12.884705       -0.304070          12.884705           0.198727   

           qed    MolWt  ...  fr_sulfide  fr_sulfonamd  fr_sulfone  \
0     0.459524  422.410  ...           0             0           0   
1     0.490285  402.389  ...           0             0           0   
2     0.473622  418.844  ...           0             0           0   
3     0.605781  306.329  ...           0             0           0   
4     0.425341  476.606  ...           0             0           1   
...        ...      ...  ...         ...           ...         ...   
3266  0.457796  520.993  ...           0             0           0   
3267  0.441622  538.983  ...           0             0           0   
3268  0.379282  495.587  ...           0             0           0   
3269  0.745476  267.288  ...           0             0           0   
3270  0.284615  527.629  ...           0             0           0   

      fr_term_acetylene  fr_tetrazole  fr_thiazole  fr_thiocyan  fr_thiophene  \
0                     0             0            0            0             0   
1                     0             0            0            0             0   
2                     0             0            0            0             0   
3                     0             0            0            0             0   
4                     0             0       

In [40]:
# X = data[['MinEStateIndex', 'BCUT2D_MRHI', 'PEOE_VSA12', 'PEOE_VSA6', 'SMR_VSA2',
#        'SMR_VSA6', 'SlogP_VSA8', 'VSA_EState5', 'NumAliphaticCarbocycles',
#        'NumAromaticCarbocycles', 'NumAromaticRings', 'fr_Ar_N', 'fr_Ar_NH',
#        'fr_aniline', 'fr_imidazole']]
X = data[data.columns[4:]]
y = data[data.columns[2]]

In [41]:
X

MaxEStateIndex  MinEStateIndex  MaxAbsEStateIndex  MinAbsEStateIndex  \
0          12.917910       -4.483900          12.917910           0.071660   
1          14.243005       -0.439546          14.243005           0.185077   
2          12.889483       -0.245588          12.889483           0.239832   
3           5.152457        0.533437           5.152457           0.533437   
4          12.168844       -3.377002          12.168844           0.235711   
...              ...             ...                ...                ...   
3266       13.863638       -1.178358          13.863638           0.023255   
3267       13.884472       -3.073039          13.884472           0.006903   
3268       12.815756       -0.292129          12.815756           0.172028   
3269        9.348054        0.215911           9.348054           0.215911   
3270       12.884705       -0.304070          12.884705           0.198727   

           qed    MolWt  HeavyAtomMolWt  ExactMolWt  NumValenceElectrons  \
0     0.459524  422.410         405.274  422.135446                  156   
1     0.490285  402.389         387.269  402.124052                  148   
2     0.473622  418.844         403.724  418.094501                  148   
3     0.605781  306.329         292.217  306.122909                  114   
4     0.425341  476.606         448.382  476.199445                  176   
...        ...      ...             ...         ...                  ...   
3266  0.457796  520.993         490.753  520.200109                  194   
3267  0.441622  538.983         509.751  538.190688                  200   
3268  0.379282  495.587         466.355  495.238273                  188   
3269  0.745476  267.288         254.184  267.100777                  100   
3270  0.284615  527.629         494.365  527.264488                  202   

      NumRadicalElectrons  ...  fr_sulfide  fr_sulfonamd  fr_sulfone  \
0                       0  ...           0             0           0   
1                       0  ...           0             0           0   
2                       0  ...           0             0           0   
3                       0  ...           0             0           0   
4                       0  ...           0             0           1   
...                   ...  ...         ...           ...         ...   
3266                    0  ...           0             0           0   
3267                    0  ...           0             0           0   
3268                    0  ...           0             0           0   
3269                    0  ...           0             0           0   
3270                    0  ...           0             0           0   

      fr_term_acetylene  fr_tetrazole  fr_thiazole  fr_thiocyan  fr_thiophene  \
0                     0             0            0            0             0   
1                     0             0            0            0             0   
2                     0             0            0            0             0   
3                     0             0            0            0             0   
4                     0             0            0            0             0   
...                 ...           ...          ...          ...           ...   
3266                  0             0            0            0             0   
3267                  0             0            0            0             0   
3268                  0             0            0            0             0   
3269                  0             0            0            0             0   
3270                  0             0            0            0             0   

      fr_unbrch_alkane  fr_urea  
0                    0        0  
1                    0        0  
2                    0        0  
3                    0        0  
4                    0        0  
...                ...      ...  
3266                 0        0  
3267                 0        0  
3268        

In [42]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)




In [43]:
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [44]:
y_train = y_train.values
y_train
y_test = y_test.values
y_test

array([ 9.26,  6.7 ,  5.  ,  6.21,  7.92,  9.26, 10.26,  6.97,  6.25,
        4.79,  6.6 ,  8.6 ,  9.26,  8.92,  6.87,  6.63,  7.48,  6.59,
        8.89,  6.14,  7.96,  8.19,  7.05,  6.84,  5.24,  8.1 ,  7.94,
       10.28,  8.74,  8.52,  8.25,  6.95,  5.08,  8.82,  5.96,  9.4 ,
        6.6 ,  5.75,  8.96,  6.32,  7.26,  5.92,  7.34,  9.26,  7.52,
        7.28,  6.21,  8.18,  7.2 ,  7.29,  9.11,  9.52,  6.41,  7.07,
        7.37,  6.66,  6.87,  5.75,  5.84,  5.67,  5.6 ,  6.28,  7.76,
        4.84,  7.  ,  6.5 ,  5.72,  7.25,  7.75,  5.78,  5.19,  6.18,
        5.92,  6.85,  9.16,  6.68,  5.72,  7.1 ,  7.19,  6.72,  7.89,
        6.96,  5.96,  8.89,  7.47,  9.  ,  5.35,  6.19,  7.04,  6.7 ,
        6.61,  7.46,  6.58,  6.05,  6.24,  7.54,  7.15,  5.94,  6.62,
        6.82,  5.62,  9.26,  8.55,  5.17,  6.71,  8.62,  9.3 ,  5.19,
        6.81,  5.54,  6.53,  6.19,  6.89,  5.07,  6.57,  7.2 ,  5.18,
        5.95,  8.96,  5.29,  6.76,  5.92,  7.02,  6.91,  7.  ,  6.  ,
        6.68,  8.05,

In [45]:
X_test

array([[0.41386662, 0.90424766, 0.41386662, ..., 0.        , 0.        ,
        0.        ],
       [0.80594283, 0.86126983, 0.80594283, ..., 0.        , 0.        ,
        0.        ],
       [0.81278962, 0.35072889, 0.81278962, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.94116265, 0.33287607, 0.94116265, ..., 0.        , 0.        ,
        0.        ],
       [0.8382802 , 0.44426293, 0.8382802 , ..., 0.        , 0.        ,
        0.        ],
       [0.79980523, 0.83336431, 0.79980523, ..., 1.        , 0.        ,
        0.        ]])

In [46]:
y

0       7.70
1       7.52
2       6.77
3       6.29
4       6.85
        ... 
3266    8.89
3267    8.92
3268    8.70
3269    7.40
3270    8.51
Name: pChEMBL Value, Length: 3271, dtype: float64

In [47]:
X.shape

(3271, 208)

In [48]:
from torch.utils.data import DataLoader, TensorDataset
import os
import torch
import wandb
from torch import nn
import torch.nn.functional as F
import pytorch_lightning as pl
from torch.utils.data import DataLoader
from pytorch_lightning.loggers import WandbLogger

In [49]:
class NeuralNetwork(pl.LightningModule):
    def __init__(self, input_sz, hidden_sz, train_data, test_data, batch_size=254, lr=1e-3):
        super().__init__()
        self.lr = lr
        self.train_data = train_data
     
        self.test_data = test_data
        self.batch_size = batch_size
        
        # Define all the components
        self.model = nn.Sequential(
            nn.Linear(input_sz, hidden_sz),
            nn.ReLU(),
            nn.Linear(hidden_sz, hidden_sz),
            nn.ReLU(),
            nn.Linear(hidden_sz, 1)
        )
        
    def training_step(self, batch, batch_idx):
        # Here we define the train loop.
        x, y = batch
        z = self.model(x)
        loss = F.mse_loss(z, y)
        self.log("Train loss", loss)
        return loss
    
        
    def test_step(self, batch, batch_idx):
        # What to do in test
        x, y = batch
        z = self.model(x)
        loss = F.mse_loss(z, y)  # report MSE
        self.log("Test MSE", loss)

    def configure_optimizers(self):
        # Here we configure the optimization algorithm.
        optimizer = torch.optim.Adam(
            self.parameters(),
            lr=self.lr
        )
        return optimizer
    
    def forward(self, x):
        # Here we define what the NN does with its parts
        return self.model(x).flatten()
    
    def train_dataloader(self):
        return DataLoader(self.train_data, batch_size=self.batch_size, shuffle=True)

    
    def test_dataloader(self):
        return DataLoader(self.test_data, batch_size=self.batch_size, shuffle=False)

In [50]:
X_train

array([[0.92102715, 0.82519871, 0.92102715, ..., 0.        , 0.        ,
        0.        ],
       [0.72543581, 0.87481797, 0.72543581, ..., 0.        , 0.        ,
        0.        ],
       [0.78653175, 0.48005968, 0.78653175, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.60682532, 0.8342984 , 0.60682532, ..., 0.        , 0.        ,
        0.        ],
       [0.69484997, 0.49207506, 0.69484997, ..., 0.        , 0.        ,
        0.        ],
       [0.85233167, 0.83107407, 0.85233167, ..., 0.        , 0.        ,
        0.        ]])

In [51]:
from torch.utils.data import Dataset
import numpy as np
import torch
class ESOLDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        
        if torch.is_tensor(idx):
            idx = idx.tolist()
            return self.X[idx], self.y[idx]
        X_ = torch.as_tensor(self.X[idx].astype(np.float32))
        y_ = torch.as_tensor(self.y[idx].astype(np.float32).reshape(-1))
        
        return X_, y_
    


In [52]:
train_data = ESOLDataset(X_train, y_train)

test_data = ESOLDataset(X_test, y_test)

In [53]:
train_data[0]

(tensor([9.2103e-01, 8.2520e-01, 9.2103e-01, 3.8732e-01, 5.0000e-01, 3.6726e-01,
         3.8539e-01, 3.6760e-01, 3.5514e-01, 0.0000e+00, 4.6905e-01, 3.1438e-01,
         6.8562e-01, 5.6279e-01, 4.4270e-01, 6.5961e-01, 7.9769e-01, 3.7721e-02,
         9.6053e-01, 3.3380e-01, 5.6401e-01, 4.9281e-01, 5.0805e-01, 3.4020e-02,
         3.9139e-01, 6.1565e-01, 6.3254e-01, 3.8966e-01, 3.5756e-01, 3.3328e-01,
         4.1013e-01, 3.5849e-01, 3.2215e-01, 4.0614e-01, 3.1767e-01, 4.3838e-01,
         3.1842e-01, 4.3561e-01, 3.0121e-01, 4.1129e-01, 2.5581e-05, 2.8479e-01,
         1.8550e-01, 1.1573e-01, 3.6595e-01, 2.1081e-01, 5.6320e-01, 1.8988e-01,
         2.0451e-01, 0.0000e+00, 1.7038e-01, 3.0637e-01, 4.9754e-01, 9.4187e-02,
         0.0000e+00, 2.7273e-01, 1.9421e-01, 7.1969e-02, 4.6420e-01, 1.5078e-01,
         3.0404e-01, 0.0000e+00, 6.6162e-01, 0.0000e+00, 1.4061e-01, 7.5586e-02,
         4.9931e-01, 0.0000e+00, 2.5903e-01, 3.2685e-01, 8.5835e-02, 2.4859e-01,
         0.0000e+00, 2.6431e

In [54]:
# This will ask you to login to your wandb account

wandb.init(project="pChembl value prediction",
           config={
               "batch_size": 32,
               "learning_rate": 0.001,
               "hidden_size": 512,
               "max_epochs": 100
           })

In [55]:
# Here we create an instance of our neural network.
# Play around with the hyperparameters!
nn_model = NeuralNetwork(
    input_sz = X_train.shape[1],
    hidden_sz = wandb.config["hidden_size"],
    train_data = train_data,
    test_data = test_data,
    lr = wandb.config["learning_rate"],
    batch_size=wandb.config["batch_size"]
)

# Define trainer: How we want to train the model
wandb_logger = WandbLogger()
trainer = pl.Trainer(
    max_epochs = 100,
    logger = wandb_logger
)

# Finally! Training a model :)
trainer.fit(
    model=nn_model,
)

# Now run test
results = trainer.test(ckpt_path="best")
wandb.finish()


GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/Users/sefunmibodun/anaconda3/envs/dami/lib/python3.11/site-packages/pytorch_lightning/loggers/wandb.py:390: There is a wandb run already in progress and newly created instances of `WandbLogger` will reuse this run. If this is not desired, call `wandb.finish()` before instantiating `WandbLogger`.

  | Name  | Type       | Params
-------------------------------------
0 | model | Sequential | 370 K 
-------------------------------------
370 K     Trainable params
0         Non-trainable params
370 K     Total params
1.481     Total estimated model params size (MB)
/Users/sefunmibodun/anaconda3/envs/dami/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:441: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_worke

Epoch 99: 100%|██████████| 82/82 [00:00<00:00, 119.89it/s, v_num=goqt]

`Trainer.fit` stopped: `max_epochs=100` reached.


Epoch 99: 100%|██████████| 82/82 [00:00<00:00, 117.07it/s, v_num=goqt]


Restoring states from the checkpoint path at ./lightning_logs/l1itgoqt/checkpoints/epoch=99-step=8200.ckpt
Loaded model weights from the checkpoint at ./lightning_logs/l1itgoqt/checkpoints/epoch=99-step=8200.ckpt
/Users/sefunmibodun/anaconda3/envs/dami/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:441: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.


Testing DataLoader 0: 100%|██████████| 21/21 [00:00<00:00, 157.78it/s]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       Test metric             DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        Test MSE            0.6854454874992371
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


wandb: WARNING Source type is set to 'repo' but some required information is missing from the environment. A job will not be created from this run. See https://docs.wandb.ai/guides/launch/create-job


In [56]:
f(X)

NameError: name 'f' is not defined

In [ ]:
y

tensor([7.7000, 7.5200, 6.7700,  ..., 8.7000, 7.4000, 8.5100])

In [ ]:
L(f(X), y)

tensor(1.1417, grad_fn=<MseLossBackward0>)

In [ ]:
class MyNeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.Matrix1 = nn.Linear(3, 8, bias=False)
        self.Matrix2 = nn.Linear(8, 1, bias = False)

    def forward(self, x):  
        x = self.Matrix1(x)
        x = self.Matrix2(x)
        return x.squeeze()
    

f = MyNeuralNetwork()
opt = SGD(f.parameters(), lr=0.001)
L = nn.MSELoss()


losses = []

for i in range(50):
    opt.zero_grad() #remove previous gradient
    loss_value = L(f(a), b) #calculate loss
    loss_value.backward() #compute gradient
    opt.step() #perform iteration using the gradient just calculated
    losses.append(loss_value.item()) # add loss to the array above

In [ ]:
y

tensor([7.7000, 7.5200, 6.7700,  ..., 8.7000, 7.4000, 8.5100])

In [ ]:
a = torch.tensor([[1,2,3,1,2,3,1,2,3], [4,5,6,4,5,6,4,5,6], [7,8,9,7,8,9,7,8,9] ], dtype=torch.float32)

In [ ]:
a

tensor([[1., 2., 3., 1., 2., 3., 1., 2., 3.],
        [4., 5., 6., 4., 5., 6., 4., 5., 6.],
        [7., 8., 9., 7., 8., 9., 7., 8., 9.]])

In [ ]:
b = y[1:4]

In [ ]:
b

tensor([7.5200, 6.7700, 6.2900])

In [ ]:
class MyNeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.Matrix1 = nn.Linear(9, 208, bias=False)
        self.Matrix2 = nn.Linear(208, 1, bias = False)

    def forward(self, x):  
        x = self.Matrix1(x)
        x = self.Matrix2(x)
        return x.squeeze()
    

f = MyNeuralNetwork()
opt = SGD(f.parameters(), lr=0.001)
L = nn.MSELoss()


losses = []

for i in range(5000):
    opt.zero_grad() #remove previous gradient
    loss_value = L(f(a), b) #calculate loss
    loss_value.backward() #compute gradient
    opt.step() #perform iteration using the gradient just calculated
    losses.append(loss_value.item()) # add loss to the array above
    print(loss_value.item())

50.51654052734375
396.7827453613281
2989.503173828125
16.404794692993164
94.27145385742188
1527.4320068359375
12399.6591796875
639198.9375
279507763200.0
2.814379544181181e+28
inf
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan


In [ ]:
from torch.utils.data import Dataset, DataLoader
import torchvision

class CTDataset(Dataset):
    def __init__(self, filepath):
        self.x, self.y = torch.load(filepath)
        self.x = self.x / 255.
        self.y = F.one_hot(self.y, num_classes=10).to(float)
    def __len__(self): 
        return self.x.shape[0]
    def __getitem__(self, ix): 
        return self.x[ix], self.y[ix]

UnpicklingError: could not find MARK